### ISSUE TITLE
Invalid Hook Call

### ISSUE THREAD

**Issue by ButlerBorst** [jodhman/react-eyedrop#29] opened 2021-02-22 17:55 UTC
Been trying to get this package to work inside a functional component to no avail. Keep getting an invalid hook call warning. 
I've tried importing both two ways.

`import {Eyedropper} from 'react-eyedrop`
&
`import Eyedropper from 'react-eyedrop'`

and then in my return am using the base example onChange call. 

`<Eyedropper onChange={myOnChange} />`

**Comment by jodhman** [comment] 2021-02-22 19:54
Hey @ButlerBorst! I would love to help.

Could you share how to reproduce the issue you're having? Alternatively a minimal example of the code where you're implementing react-eyedrop.

That will help me pinpoint the problem you're experiencing. :-)

**Comment by jodhman** [comment] 2021-02-23 20:02
I might've stumbled on your issue while working on it today.
Just released a new version `5.0.4`. Go ahead & try that. 🙂 
Let me know if the issue persists!

**Comment by ButlerBorst** [comment] 2021-02-24 17:31
Awesome, thx for the bump. I'll be testing this out this afternoon and will report my results. If I still have the issue I'll leave more details about my use case, and if it's fixed I'll close the issue.

**Comment by ButlerBorst** [comment] 2021-02-26 22:39
@jodhman Your fix for incorporating this in a functional component seems to have worked! I see the component rendering. However when I click to pick a color I'm now getting a type error. My react project is utilizing typescript for what it's worth.

![Uploading Screen Shot 2021-02-26 at 2.35.54 PM.png…]()

For clarity here is my current setup of the Eyedropper. There's more going on in the component than this, but this is what's pertinent to the eyedropper. Once I see that log fire I should be good to go. Thanks for your help on this. Looking forward to utilizing as a component for the project. 

`import { EyeDropper } from 'react-eyedrop

function onChange({ rgb, hex }: any) {
    console.log(rgb, hex)
}

<EyeDropper onChange={onChange} />
'

**Comment by jodhman** [comment] 2021-02-26 23:37
@ButlerBorst I'm glad to hear it!
It seems like the image upload didn't go through - can't see the type error. 😞 

Something I could be more clear about in the README is a type for the onChange parameters:
https://github.com/jodhman/react-eyedrop/blob/d6fe8932f151483db3b43542b932a145ddccf70b/src/types.ts#L7-L11
so..
```
import { EyeDropper } from 'react-eyedrop

function onChange({ rgb, hex }: **OnChangeEyedrop** ) { console.log(rgb, hex) }

<EyeDropper onChange={onChange} />
```

**Comment by ButlerBorst** [comment] 2021-02-26 23:44
<img width="1665" alt="Screen Shot 2021-02-26 at 3 44 40 PM" src="https://user-images.githubusercontent.com/48074229/109366932-90aaf200-7849-11eb-9612-026343623b0c.png">

**Comment by ButlerBorst** [comment] 2021-02-26 23:45
I don't think it's the actually typing of the {rgb, hex} that is the issue. Apologies, looks like my first screen shot didn't go through.

**Comment by jodhman** [comment] 2021-02-27 12:08
Just tried something in v. `5.0.5`. Let me know if that solves it! :slightly_smiling_face:

**Comment by ButlerBorst** [comment] 2021-03-01 17:34
Getting a similar, but different error. I am still using the OnChangeEyeDrop as prop type and am on version 5.0.5. Will test again when there's an update 

<img width="493" alt="Screen Shot 2021-03-01 at 9 32 19 AM" src="https://user-images.githubusercontent.com/48074229/109535133-0e9d1200-7a71-11eb-872f-5facd0d44a34.png">

**Comment by jodhman** [comment] 2021-03-03 20:57
Damm... Alright. I'm gonna have to try & reproduce it locally.
I'll let you know once I have!

**Comment by ButlerBorst** [comment] 2021-03-03 23:00
Sounds good! Good luck to ya. Let me know if you need any other info on my end.

**Comment by jodhman** [comment] 2021-03-29 10:24
Wanted to give a quick heads-up; you're not forgotten.
Been super-busy these past few weeks.
Will soon find enough time to go through it thoroughly.

**Comment by ButlerBorst** [comment] 2021-03-29 16:13
Thx for the update! Let me know if I can be of any help. Could even find time to screen share if it would be helpful.

**Comment by justinpchang** [comment] 2021-03-31 14:25
@ButlerBorst @jodhman I hit the same problem. If you check out lines 117 and 118 of eyeDropper.tsx:
```
const { offsetX, offsetY } = e
html2canvas.default(target, { logging: false })
.then(...
```
It seems like the transpiled JS combines those lines into `... e(html2canvas).default...`

The solution should be to use semicolons strictly throughout the package.

**Comment by justinpchang** [comment] 2021-03-31 14:33
@jodhman To reproduce, create a new project using the npm installed package rather than the source. Then use the eyedropper as normal and the error will appear. I installed source in my project and placed semicolons everywhere and it worked. I can submit a PR this weekend.

**Comment by jodhman** [comment] 2021-03-31 22:13
Wow! Nicely caught, @justinpchang.
I'll gladly merge in your PR then :tada:

**Comment by jodhman** [comment] 2021-04-04 23:47
@ButlerBorst 
Go ahead & give 5.1.0 a try :slightly_smiling_face:

**Comment by mfouquet** [comment] 2021-04-06 15:17
@jodhman Dropping in here since I also had the same issue. 5.1.0 fixed this issue for me (`e is not a function`): https://github.com/jodhman/react-eyedrop/issues/29#issuecomment-788132934

But now this one is back (`html2canvas.default is not a function`): https://github.com/jodhman/react-eyedrop/issues/29#issuecomment-786952749

**Comment by jodhman** [comment] 2021-04-07 17:21
Got it to work locally with v. `5.1.1`.
Please let me know if that works for you :relaxed:

**Comment by jodhman** [comment] 2021-04-21 16:13
Closing as someone else confirmed it working:
https://github.com/jodhman/react-eyedrop/issues/30

**Closed** 2021-04-21 16:14 UTC
